# This is a basic workflow to help you get started with Actions

name: Create milestone
# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: 'Create new milestone'
        id: createmilestone
        
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: 'test2'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
