name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release
        uses: jaeseokk/release-action@dev
        with:
          lastCommitMessage: ${{ github.event.head_commit.message }}
