name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Release
        uses: jaeseokk/release-action@main
        with:
          slackToken: ${{ secrets.SLACK_TOKEN }}
          slackChannel: jaeseokk_test
